name: "Gemini PR Reviewer"
description: "Automatically reviews PRs using Gemini"
author: "igorschechtel"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository"
    required: true
  GEMINI_API_KEY:
    description: "Google Gemini API key"
    required: true
  GEMINI_MODEL:
    description: "Gemini model to use"
    required: false
    default: "gemini-flash-latest"
  REVIEW_MODE:
    description: "Review mode: standard | strict | lenient | security | performance"
    required: false
    default: "standard"
  REVIEW_INSTRUCTIONS:
    description: "Additional review instructions appended to the prompt"
    required: false
    default: ""
  COMMAND_TRIGGER:
    description: "Comment trigger text"
    required: false
    default: "/gemini-review"
  EXCLUDE:
    description: "Comma-separated glob patterns to exclude"
    required: false
    default: ""
  INCLUDE:
    description: "Comma-separated glob patterns to include"
    required: false
    default: ""
  MAX_FILES:
    description: "Max files to review"
    required: false
    default: "50"
  MAX_HUNKS_PER_FILE:
    description: "Max hunks per file"
    required: false
    default: "20"
  MAX_LINES_PER_HUNK:
    description: "Max lines per hunk"
    required: false
    default: "500"
  GLOBAL_REVIEW:
    description: "Enable a global PR-level review pass"
    required: false
    default: "true"
  GLOBAL_MAX_LINES:
    description: "Max total diff lines for the global review pass"
    required: false
    default: "2000"

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun install

    - name: Run Gemini PR Reviewer
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        GEMINI_MODEL: ${{ inputs.GEMINI_MODEL }}
        REVIEW_MODE: ${{ inputs.REVIEW_MODE }}
        REVIEW_INSTRUCTIONS: ${{ inputs.REVIEW_INSTRUCTIONS }}
        COMMAND_TRIGGER: ${{ inputs.COMMAND_TRIGGER }}
        EXCLUDE: ${{ inputs.EXCLUDE }}
        INCLUDE: ${{ inputs.INCLUDE }}
        MAX_FILES: ${{ inputs.MAX_FILES }}
        MAX_HUNKS_PER_FILE: ${{ inputs.MAX_HUNKS_PER_FILE }}
        MAX_LINES_PER_HUNK: ${{ inputs.MAX_LINES_PER_HUNK }}
        GLOBAL_REVIEW: ${{ inputs.GLOBAL_REVIEW }}
        GLOBAL_MAX_LINES: ${{ inputs.GLOBAL_MAX_LINES }}
      run: bun run src/index.ts
